// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLApGfbPoEzqQ5QSU3fQvyRBEymLcBVz0',
    appId: '1:638555295008:web:e6270fd6271d12f6f61b45',
    messagingSenderId: '638555295008',
    projectId: 'grootantest-71a14',
    authDomain: 'grootantest-71a14.firebaseapp.com',
    storageBucket: 'grootantest-71a14.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDr67uuEj-e8Fo_td6WTl4y72J6CtADn4s',
    appId: '1:638555295008:android:a97b7a8698df12ebf61b45',
    messagingSenderId: '638555295008',
    projectId: 'grootantest-71a14',
    storageBucket: 'grootantest-71a14.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpjgF_OtSmb1k3fRye5VI3dwGDQFcwBZs',
    appId: '1:638555295008:ios:14b7a47a3c058127f61b45',
    messagingSenderId: '638555295008',
    projectId: 'grootantest-71a14',
    storageBucket: 'grootantest-71a14.appspot.com',
    androidClientId: '638555295008-59r7fbvc2e2tota882qj3cjj33qm197j.apps.googleusercontent.com',
    iosClientId: '638555295008-6trab9c5gqamjdde7gok42bgst5re2sv.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce',
  );
}
