name: CI Pipeline

on:
  push:
    branches:
      - main  # triggers only when PR is merged into main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5' # replace with your Flutter version

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # 6️⃣ (Optional) Build release APK
      - name: Build release APK
        run: flutter build apk --release
